package com.github.said1296.mqttcontroller.configurations

import org.springframework.boot.context.properties.EnableConfigurationProperties

@EnableConfigurationProperties(MqttControllerProperties::class)
class MqttControllerConfiguration
